name: Regression suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '30 20 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          REPORT_DIR="reports"
          mkdir -p $REPORT_DIR
          TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")
          REPORT_FILE="$REPORT_DIR/Automation_report_$TIMESTAMP.html"
          pytest --html=$REPORT_FILE --self-contained-html
          echo "REPORT_FILE=$REPORT_FILE" >> $GITHUB_ENV

      - name: Upload pytest report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: ${{ env.REPORT_FILE }}

      - name: Send Email with Report
        uses: dawidd6/action-send-mail@v3
        with:
          # Email configuration
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Pytest Automation Report"
          to: "recipient@example.com" # Replace with recipient email
          from: "sender@example.com" # Replace with sender email
          content_type: text/html
          body: |
            <p>Hi,</p>
            <p>Please find the attached automation report.</p>
            <p>Thanks,</p>
          attachments: ${{ env.REPORT_FILE }}
