name: Regression suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '30 20 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")
          pytest --html=reports/report_$TIMESTAMP.html --self-contained-html

      - name: Send Test Report via Email
        env:
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          subject: "Pytest Automation Report"
          to: "rajamegam7@gmail.com"
          from: "rajamegam.govindaraj@ideas2it.com"
          content_type: text/html
          body: |
            Hi,
            Please find the attached automation report.
            Thanks,
        run: |
          python Utils/email_utils.py

     

#name: Run Pytest and Send Report
#
#on:
#  push:
#    branches:
#      - main  # Run this workflow on pushes to the main branch
#  pull_request:  # Optional: Run on pull requests
#  workflow_dispatch:  # Allow manual triggering of the workflow
#
#jobs:
#  test-and-email:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.12.2"
#
#      - name: Install dependencies
#        run: |
#          pip install -r requirements.txt
#          pip install pytest pytest-html
#
#      - name: Run Pytest
#        run: |
#          TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")
#          pytest --html=reports/report_$TIMESTAMP.html --self-contained-html
#
#      - name: Send Test Report via Email
#        env:
#          SMTP_SERVER: smtp.gmail.com
#          SMTP_PORT: 587
#          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
#          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
#          subject: "Pytest Automation Report"
#          to: "rajamegam7@gmail.com"
#          from: "rajamegam.govindaraj@ideas2it.com"
#          content_type: text/html
#          body: |
#            Hi,
#            Please find the attached automation report.
#            Thanks,
#        run: |
#          python send_email.py
